baseURL = 'https://www.investingfilter.com/'
languageCode = 'en-us'
title = 'Investing Filter'
theme = 'PaperMod'

[params]
  math = true
  ShowPageNavigation = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowToc = true
  ShowPostNavLinks = true
  enableEmoji = true
  showtoc = true
  hideMeta = false
  mainSections = ["posts"]
  enableDropdownMenu = true

  [params.social]
    twitter = ""
    facebook_admin = ""

  [params.profileMode]
    enabled = true
    title = "Investing Filter"
    subtitle = "Tools and insights for filtering investment opportunities."
    imageUrl = "/images/profile.png"
    imageTitle = "Investing Filter Logo"
    imageWidth = 120
    imageHeight = 120

  [params.assets]
    favicon = "/images/profile.png"
    favicon16x16 = "/images/profile.png"
    favicon32x32 = "/images/profile.png"
    apple_touch_icon = "/images/profile.png"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "📝 Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "ℹ️ About"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "rental-yield-calculator"
    name = "🏠 Rental Yield Calculator"
    url = "/rental-yield-calculator/"
    weight = 15

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
